### PR TITLE
feat: Search managed policy from IAM action

### LINKED ISSUE #6: Allow searching for managed policies containing a permission
This is a super useful tool and I've started linking colleagues to this rather than AWS' own IAM docs as it looks much clearer plus has the benefit of listing managed IAM policies without them needing to log into the AWS console to view.

One thing that would be useful for me would be to be able to search all managed policies for a specific permission. Right now I go to the source repo and search via GitHub (eg like [this](https://github.com/iann0036/iam-dataset/search?q=ImportExternalIdPCertificate)) but it would be a nicer user experience if you could go from eg [this link](https://aws.permissions.cloud/iam/sso-directory#sso-directory-ImportExternalIdPCertificate) and then click into a permission to see managed policies containing the effective action.

### PR DESCRIPTION
**Pull request by exoego**
Closes https://github.com/iann0036/aws.permissions.cloud/issues/6

Depends on https://github.com/iann0036/iam-dataset/pull/31

## 1. Search managed policies by action

The search modal can show "Managed Policies" that contains the search term (IAM action).

image

I've dropped https://github.com/iann0036/aws.permissions.cloud/pull/8/commits/06cc35b2ca803efac5e43b66df12174c1dcd2146 and https://github.com/iann0036/aws.permissions.cloud/pull/8/commits/116c4d318ac9c727f1612a98ed6cb23f4d9e5589 since those are controversial.

<details>
<summary>dropped from this PR</summary>

## 2. Quick-search by clicking action

IAM action names are now linked to search.

When user clicks the action name,
image

It opens a search modal showing the matched managed policies.
image

## 3. Dedicated page for Managed Policies for Service

Each service now has a third page: Managed Policies for Service.
The new page shows the list of managed policies that contain IAM Actions for the service.
image

As a consequence, I've tweaked buttons/tabs as described below:
image
</details>

### CODE REVIEW

**Comment by iann0036** [comment]
Do you have an idea on how we'd represent this data? Maybe we could have a dedicated page view for an IAM action's detail, however I would like to keep the main list view as the primary reference where possible. 🤔

**Comment by exoego** [comment]
> Maybe we could have a dedicated page view for an IAM action

That was my first thought, but a new dedicated page requires much effort.
I will consider a more minimal approach.

----
After consideration, I think it is better to have 3rd page to show Managed Policies for each Service.

**Comment by iann0036** [comment]
Hey @exoego,

Still analysing this one. I'm still pondering how to support a managed policies for _action_ view, however I'm unlikely to accept a managed services for service view as it has some weird consequences and services are somewhat more vague than pure actions.

**Comment by exoego** [comment]
@exoego I've excluded 
- link from action name to search modal
- a managed-policy-for-action view
which are controversial

**Comment by iann0036** [comment]
Thanks @exoego,

I'll merge this one now. If you could keep your branch around whilst we figure out the best way to include the view, that'd be great. We'll use the majority of it...eventually.

**Review by iann0036 — APPROVED** [review]

**Comment by iann0036** [comment]
@exoego I'm thinking about something like:
Screenshot 2023-10-07 at 2 08 47 pm

**Pull request merged**
